services:
  server:
    env_file:
      - path: ./.env
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./.data/static:/static
      - ./.data/media:/media
      - ./.data/db.sqlite3:/app/.data/db.sqlite3