services:
  server:
    env_file:
      - .env
    build:
      context: .
      network: host
    ports:
      - 8000:8000
    volumes:
      - ./.data:/app/.data
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
