# Generated by Django 5.0.4 on 2024-05-24 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Новостной пост', 'verbose_name_plural': 'Новостные посты'},
        ),
    ]
