# Generated by Django 5.0.4 on 2024-05-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.TextField(verbose_name='Имя')),
                ('email', models.EmailField(max_length=255, verbose_name='Почта')),
                ('topic', models.TextField(verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Обратная связь пользователя',
                'verbose_name_plural': 'Обратная связь пользователей',
            },
        ),
    ]
