# Generated by Django 5.0.4 on 2024-05-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Feedback',
        ),
    ]
